nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

npmScopes:
  cerc-io:
    npmRegistryServer: https://git.vdb.to/api/packages/cerc-io/npm/
